trigger:
  branches:
    include:
      - main  # Change this to your branch name if needed

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image for the build agent

variables:
  imageName: 'precision-farming-app'  # Name of the Docker image
  tag: 'latest'  # Tag for the Docker image
  acrName: 'raghackathon'  # Your ACR name
  registry: '$(acrName).azurecr.io'  # Fully qualified name of your ACR

stages:
- stage: BuildAndPush
  jobs:
  - job: Build
    steps:
    - checkout: self  # Check out the code from the repository

    - task: Docker@2
      displayName: 'Build and push Docker image'
      inputs:
        containerRegistry: 'ACRServiceConnection'  # Name of your Docker Registry service connection
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'  # Adjust the path if your Dockerfile is not at the root
        tags: |
          $(tag)
